### ISSUE TITLE
Support Concourse 5.x

### ISSUE THREAD

**Issue by initharrington** [walkamongus/puppet-concourse#1]
Concourse 5.x was released March 6th.  This module does not support 5.x due to breaking changes.  The primary breaking change with the 5.x release was the following:
https://concourse-ci.org/download.html#v500-note-3

"The concourse binary distribution has been rejiggered. Rather than a self-contained binary, we now ship it as a .tgz containing the binary and its dependencies pre-extracted. The .tgz should be extracted somewhere like /usr/local, resulting in /usr/local/concourse/bin/...."

I forked this module into a local repo and have it running on 5.1.0.  The code I wrote isn't backwards compatible.  If you want to help make sure it is, that would be great!

I'll make a PR soon.

**Comment by walkamongus** [comment]
fixed with #4
